####
#
#
###
FROM registry.access.redhat.com/ubi9/python-311

ENV LANG='en_US.UTF-8' LANGUAGE='en_US:en'


# We make four distinct layers so if there are application changes the library layers can be re-used



EXPOSE 8080
USER 185
